version: "3.9"
    
services:
  db:
    container_name: wp_db
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - ./mysql/lib:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    
  wordpress:
    container_name: wp_web
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ~/Development/wp-local/wordpress:/var/www/html
    ports:
      - "8000:80"
    restart: always
    build:
      context: ./php
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wordpress_data: {}